

import java.awt.Frame;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import pdf_divider.PDF_Divider;


public class NewJFrame extends javax.swing.JFrame {

    
    
    private static String PDFPath="";
    private static String outputPath="result";
    
    private static boolean type1Active;
    private static boolean type2Active;
    private static boolean type3Active;
    
    private static boolean aActive=true;
    private static boolean bActive=false;
    
    private static boolean aandbEnable;
    
    
    private static int n=1;
    private static String stringN="1";
    
    private static int x1=1;
    private static int x2=1;
    
    private static boolean n1Enabled;
    private static boolean n2Enabled;
    private static boolean n3Enabled;
    
    
    private static boolean allPages;
    private static int firstPage;
    private static int lastPage;
    
    private static int numberofpages=0;
    
    
    private static boolean checked;
    
    private void myInit(){
        allPages=true;
        allPageRB.setSelected(true);
        outputText.setText(outputPath);
        modN=2;
        stringModN="2";
        n3.setText(stringModN);
        update();
    }
    
    public NewJFrame() {
        initComponents();
        myInit();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        inputText = new javax.swing.JTextField();
        outputText = new javax.swing.JTextField();
        type1Label = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        type1 = new javax.swing.JRadioButton();
        type2 = new javax.swing.JRadioButton();
        type3 = new javax.swing.JRadioButton();
        a = new javax.swing.JRadioButton();
        b = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        n1 = new javax.swing.JTextField();
        type2Label = new javax.swing.JLabel();
        n2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        n3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        infoLabel = new javax.swing.JLabel();
        CheckButton = new javax.swing.JButton();
        allPageRB = new javax.swing.JRadioButton();
        firstPageTF = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        lastPageTF = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pdf_Divider_v1.0");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        mainPanel.setBackground(new java.awt.Color(204, 204, 204));

        type1Label.setBackground(new java.awt.Color(0, 0, 0));
        type1Label.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        type1Label.setForeground(new java.awt.Color(0, 0, 0));
        type1Label.setText("pages with x parts");

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Output Path");

        type1.setText("Type1");
        type1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                type1ActionPerformed(evt);
            }
        });

        type2.setText("Type2");
        type2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                type2ActionPerformed(evt);
            }
        });

        type3.setText("Type3");
        type3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                type3ActionPerformed(evt);
            }
        });

        a.setText("A");
        a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aActionPerformed(evt);
            }
        });

        b.setText("B");
        b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("PDF Path");

        n1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n1ActionPerformed(evt);
            }
        });
        n1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                n1KeyReleased(evt);
            }
        });

        type2Label.setBackground(new java.awt.Color(0, 0, 0));
        type2Label.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        type2Label.setForeground(new java.awt.Color(0, 0, 0));
        type2Label.setText("parts with x pages");

        n2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n2ActionPerformed(evt);
            }
        });
        n2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                n2KeyReleased(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("2 parts");

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("mod :");

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Odd pages in part 1, even pages in part 2");

        n3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n3ActionPerformed(evt);
            }
        });
        n3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                n3KeyReleased(evt);
            }
        });

        jButton1.setText("Divide");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        infoLabel.setBackground(new java.awt.Color(0, 0, 0));
        infoLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        infoLabel.setForeground(new java.awt.Color(0, 0, 0));
        infoLabel.setText("INFO");

        CheckButton.setText("Check PDF");
        CheckButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckButtonActionPerformed(evt);
            }
        });

        allPageRB.setText("all pages");
        allPageRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allPageRBActionPerformed(evt);
            }
        });

        firstPageTF.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        firstPageTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstPageTFActionPerformed(evt);
            }
        });
        firstPageTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                firstPageTFKeyReleased(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("-");

        lastPageTF.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        lastPageTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lastPageTFKeyReleased(evt);
            }
        });

        jLabel10.setBackground(new java.awt.Color(0, 0, 0));
        jLabel10.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Page Range");

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(b)
                            .addComponent(a))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(3, 3, 3)
                                .addComponent(n3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel7)))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addComponent(type2)
                                .addGap(8, 8, 8)
                                .addComponent(n2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addComponent(type1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(n1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(type2Label)
                            .addComponent(type1Label)))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(type3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(CheckButton)
                            .addComponent(jLabel10)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inputText, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addComponent(allPageRB)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(firstPageTF, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(7, 7, 7)
                                .addComponent(jLabel9)
                                .addGap(7, 7, 7)
                                .addComponent(lastPageTF, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(infoLabel)
                            .addComponent(outputText, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(outputText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(10, 10, 10)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(infoLabel)
                    .addComponent(CheckButton))
                .addGap(18, 18, 18)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(allPageRB)
                    .addComponent(firstPageTF, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lastPageTF, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(type1)
                    .addComponent(type1Label)
                    .addComponent(n1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(type2)
                    .addComponent(type2Label)
                    .addComponent(n2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(type3)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(a)
                    .addComponent(jLabel7))
                .addGap(22, 22, 22)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b)
                    .addComponent(jLabel6)
                    .addComponent(n3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lastPageTFKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lastPageTFKeyReleased
        // TODO add your handling code here:
        lastLastpage = lastPage;
        int rtn = lastLastpage;
        try {
            rtn = strToInt(lastPageTF.getText());
        } catch (Exception ex) {

        }
        lastPage = rtn;

        lastPageTF.setText(""+lastPage);

        update();
    }//GEN-LAST:event_lastPageTFKeyReleased

    private void firstPageTFKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_firstPageTFKeyReleased
        // TODO add your handling code here:
        lastFirstpage = firstPage;
        int rtn = lastFirstpage;
        try {
            rtn = strToInt(firstPageTF.getText());
        } catch (Exception ex) {

        }
        firstPage = rtn;

        firstPageTF.setText(""+firstPage);

        update();
    }//GEN-LAST:event_firstPageTFKeyReleased

    private void firstPageTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstPageTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstPageTFActionPerformed

    private void allPageRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allPageRBActionPerformed
        // TODO add your handling code here:

        allPages = allPageRB.isSelected();

        update();
    }//GEN-LAST:event_allPageRBActionPerformed

    private void CheckButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckButtonActionPerformed
        // TODO add your handling code here:

        boolean c1 = false;//path is not empty
        boolean c2 = false;//file exists
        boolean c3 = false;//file pdf

        PDFPath = inputText.getText();

        try {

            c1 = !PDFPath.equals("");

            if(c1){
                inputFile = new File(PDFPath);
                if(inputFile.exists()==false){
                    PDFPath=PDFPath.substring(1, PDFPath.length());
                    inputFile = new File(PDFPath);
                    c2 = inputFile.exists();
                }
                else
                c2 = true;
            }else{
                throw new Exception("PdfPath cannot be empty");
            }

            if(c2){

                c3 = PDF_Divider.isItPDF(PDFPath);
                numberofpages = PDF_Divider.npofPDF(PDFPath);
            }
            else{
                throw new Exception("File not found");
            }

            if(!c3)
            throw new Exception("File is not a pdf");

        } catch (Exception e) {

            JOptionPane.showMessageDialog(new Frame("ERROR"), e.getMessage());
            checked=false;
            update();
            return;

        }

        c1 = false;// c1 : path is not empty
        c2 = false;// c2 : path exists
        c3 = false;// c3 : path is a directory

        outputPath = outputText.getText();

        try {

            c1 = !outputPath.equals("");
            File cntFile;
            if(c1){
                cntFile = new File(outputPath);
                if(cntFile.exists()==false){
                    outputPath=outputPath.substring(1, outputPath.length());
                    cntFile = new File(outputPath);
                    c2 = cntFile.exists();
                }
                else
                c2 = true;
            }else{
                throw new Exception("PdfPath cannot be empty");
            }

            if(c2){

                c3 = cntFile.isDirectory();

            }
            else{
                throw new Exception("Output not found");
            }

            if(!c3)
            throw new Exception("Output is not a directory");

        } catch (Exception e) {

            JOptionPane.showMessageDialog(new Frame("ERROR"), e.getMessage());
            checked=false;
            update();
            return;

        }

        checked=true;
        update();
    }//GEN-LAST:event_CheckButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        CheckButton.doClick();
        if(checked){

            if(type1Active){

                if(n==0){
                    update();
                    return;
                }

                pdf_divider.PDF_Divider divider = new PDF_Divider();
                divider.setPDFPath(PDFPath);
                try {
                    divider.LoadPdf();
                    divider.type1(n,outputPath,removeFileExtension(inputFile.getName(), true), allPages, firstPage, lastPage);
                    JOptionPane.showMessageDialog(new Frame("successful"), "Successful");
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(new Frame("ERROR"), e.getMessage());
                }
            }
            else if(type2Active){

                if(n==0){
                    update();
                    return;
                }

                pdf_divider.PDF_Divider divider = new PDF_Divider();
                divider.setPDFPath(PDFPath);
                try {
                    divider.LoadPdf();
                    divider.type2(n,outputPath,removeFileExtension(inputFile.getName(), true), allPages, firstPage, lastPage);
                    JOptionPane.showMessageDialog(new Frame("successful"), "Successful");
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(new Frame("ERROR"), e.getMessage());
                }
            }
            else if(type3Active){

                if(!allPages&&firstPage==0){
                    update();
                    return;
                }

                pdf_divider.PDF_Divider divider = new PDF_Divider();
                divider.setPDFPath(PDFPath);
                try {
                    divider.LoadPdf();

                    divider.type3(modN, outputPath, removeFileExtension(inputFile.getName(), true), allPages, firstPage, lastPage, aActive);
                    JOptionPane.showMessageDialog(new Frame("successful"), "Successful");
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(new Frame("ERROR"), e.getMessage());
                }

            }

            System.out.println("bitti");

        }
        else{

        }

        update();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void n3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_n3KeyReleased
        // TODO add your handling code here:
        lastModN = modN;
        int rtn = lastModN;
        try {
            rtn = strToInt(n3.getText());
        } catch (Exception ex) {

        }
        modN = rtn;
        if(rtn<=1){
            modN=2;
        }

        stringModN = ""+modN;

        update();
    }//GEN-LAST:event_n3KeyReleased

    private void n3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_n3ActionPerformed

    private void n2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_n2KeyReleased
        // TODO add your handling code here:
        lastN =n;
        int rtn = lastN;
        try {
            rtn = strToInt(n2.getText());
        } catch (Exception ex) {

        }
        n = rtn;
        stringN = ""+n;

        update();
    }//GEN-LAST:event_n2KeyReleased

    private void n2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_n2ActionPerformed

    private void n1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_n1KeyReleased
        // TODO add your handling code here:

        lastN =n;
        int rtn = lastN;
        try {
            rtn = strToInt(n1.getText());
        } catch (Exception ex) {

        }
        n = rtn;
        stringN = ""+n;

        update();
    }//GEN-LAST:event_n1KeyReleased

    private void n1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_n1ActionPerformed

    private void bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bActionPerformed
        // TODO add your handling code here:

        aActive = false;
        bActive = true;

        update();
    }//GEN-LAST:event_bActionPerformed

    private void aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aActionPerformed
        // TODO add your handling code here:

        aActive = true;
        bActive = false;

        update();
    }//GEN-LAST:event_aActionPerformed

    private void type3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_type3ActionPerformed
        // TODO add your handling code here:

        type1Active=false;
        type2Active=false;
        type3Active=true;
        aandbEnable=true;

        n1Enabled=false;
        n2Enabled=false;
        n3Enabled=true;

        update();
    }//GEN-LAST:event_type3ActionPerformed

    private void type2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_type2ActionPerformed
        // TODO add your handling code here:
        type1Active=false;
        type2Active=true;
        type3Active=false;
        aandbEnable=false;

        n1Enabled=false;
        n2Enabled=true;
        n3Enabled=false;

        update();
    }//GEN-LAST:event_type2ActionPerformed

    private void type1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_type1ActionPerformed

        type1Active=true;
        type2Active=false;
        type3Active=false;
        aandbEnable=false;

        n1Enabled=true;
        n2Enabled=false;
        n3Enabled=false;

        update();
    }//GEN-LAST:event_type1ActionPerformed
    
    
    private static int lastN;
        
    private static int modN;
    private static int lastModN;
    private static String stringModN;
    
    private static File inputFile;
    
    
    int lastFirstpage;    
    int lastLastpage;
    public static String removeFileExtension(String filename, boolean removeAllExtensions) {
        if (filename == null || filename.isEmpty()) {
            return filename;
        }

        String extPattern = "(?<!^)[.]" + (removeAllExtensions ? ".*" : "[^.]*$");
        return filename.replaceAll(extPattern, "");
    }
    
    private void update(){
        
        if(!checked){
            type1.setEnabled(false);
            type2.setEnabled(false);
            type3.setEnabled(false);
            jButton1.setEnabled(false);
        }
        else{
            type1.setEnabled(true);
            type2.setEnabled(true);
            type3.setEnabled(true);
            jButton1.setEnabled(true);
        }
        
        updateTextFields();
        upgradeRadiobuttons();
        updatePageRange();
        updateLabels();
        
    }
    
    private String t1String="pages with x parts";
    private String t2String="parts with x pages";
    
    private void updateLabels(){
        
        int tnum=numberofpages;
        if(!allPages){
            tnum = lastPage-firstPage;
        }
        
        if(n>0){
            x1 = (int) Math.ceil(1.0*tnum/n);
            x2 = (int) Math.ceil(1.0*tnum/n);
        }
        else{
            x1 = 0;
            x2 = 0;
        }
        
        
        
        t1String="pages with "+x1+" parts";
        t2String="parts with "+x2+" pages";
        
        type1Label.setText(t1String);
        type2Label.setText(t2String);
        
        if(checked){
            String info="";
            info+="pages : "+(numberofpages)+" ";
            info+="name : "+ removeFileExtension(inputFile.getName(), true);
            infoLabel.setText(info);
        }
        
        
    }
    
    
    private void updatePageRange(){
        

            
        allPageRB.setEnabled(true);
        if(allPages){
            firstPageTF.setEnabled(false);
            lastPageTF.setEnabled(false);
        }
        else{
            firstPageTF.setEnabled(true);
            lastPageTF.setEnabled(true);
        }

        
    }
    
    private void updateTextFields(){
        n1.setText(stringN);
        n2.setText(stringN);
        n3.setText(stringModN);
        
        n1.setEnabled(n1Enabled);
        n2.setEnabled(n2Enabled);
        n3.setEnabled(n3Enabled&&bActive);
        
    }
    
    private void upgradeRadiobuttons(){
        
        a.setEnabled(aandbEnable&&type3.isEnabled());
        b.setEnabled(aandbEnable&&type3.isEnabled());
        
        
        if(aActive){
            a.setSelected(true);
            b.setSelected(false);
        }
        else{
            b.setSelected(true);
            a.setSelected(false);
        }
        
        if(type1Active){
            type1.setSelected(true);
            type2.setSelected(false);
            type3.setSelected(false);
        }
        else if (type2Active) {
            type1.setSelected(false);
            type2.setSelected(true);
            type3.setSelected(false);
        }
        else if (type3Active){
            type1.setSelected(false);
            type2.setSelected(false);
            type3.setSelected(true);
        }
        
        
    }
    
    
    
    private int strToInt(String val)throws Exception{
        
        if(val.equals(""))return 0;
        
        int rtn = Integer.valueOf(val);
        
        
        return rtn;
        
        
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CheckButton;
    private javax.swing.JRadioButton a;
    private javax.swing.JRadioButton allPageRB;
    private javax.swing.JRadioButton b;
    private javax.swing.JTextField firstPageTF;
    private javax.swing.JLabel infoLabel;
    private javax.swing.JTextField inputText;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField lastPageTF;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTextField n1;
    private javax.swing.JTextField n2;
    private javax.swing.JTextField n3;
    private javax.swing.JTextField outputText;
    private javax.swing.JRadioButton type1;
    private javax.swing.JLabel type1Label;
    private javax.swing.JRadioButton type2;
    private javax.swing.JLabel type2Label;
    private javax.swing.JRadioButton type3;
    // End of variables declaration//GEN-END:variables
}
